# Log Message to get the VMC parameters

std_msgs/Header header

# Attraction Parameters
float64 cam_to_target_stiffness
float64 cam_to_target_max_force
float64 cam_to_target_damping

# Repulsion Parameters
float64 repulsion_guard_max_force
float64 repulsion_guard_width
float64 repulsion_floor_max_force
float64 repulsion_floor_width

# Limit Avoidance
float64 offset_angle
float64 stiffness_deadzone
